/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author zhaojiyuan
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientJPanel
     */
    
    private VitalSignHistory vitalSignHistory;
    
    public CreatePatientJPanel(VitalSignHistory vitalSignHistory) {
        initComponents();
        this.vitalSignHistory = vitalSignHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patientNameJTextField = new javax.swing.JTextField();
        patientIDJTextField = new javax.swing.JTextField();
        ageJTextField = new javax.swing.JTextField();
        primaryDoctorNameJTextField = new javax.swing.JTextField();
        preferredPharmacyJTextField = new javax.swing.JTextField();
        okayJButton = new javax.swing.JButton();

        jLabel1.setText("Create a Patient");

        jLabel2.setText("Patient Name");

        jLabel3.setText("Patient ID");

        jLabel4.setText("Age");

        jLabel5.setText("Primary Doctor Name");

        jLabel6.setText("Preferred Pharmacy");

        patientNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameJTextFieldActionPerformed(evt);
            }
        });

        okayJButton.setText("Okay");
        okayJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(patientIDJTextField)
                    .addComponent(ageJTextField)
                    .addComponent(primaryDoctorNameJTextField)
                    .addComponent(preferredPharmacyJTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okayJButton)
                    .addComponent(jLabel1))
                .addGap(335, 335, 335))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(patientNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(patientIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(primaryDoctorNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(preferredPharmacyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(okayJButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameJTextFieldActionPerformed

    private void okayJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayJButtonActionPerformed
        // TODO add your handling code here:
        try {
            String patientName = patientNameJTextField.getText();
            String patientID = patientIDJTextField.getText();
            String age = ageJTextField.getText();
            String primaryDoctorName = primaryDoctorNameJTextField.getText();
            String preferredPharmacy = preferredPharmacyJTextField.getText();

            vitalSignHistory.setPatientName(patientName);
            vitalSignHistory.setPatientID(Integer.parseInt(patientID));
            vitalSignHistory.setAge(Integer.parseInt(age));
            vitalSignHistory.setPrimaryDoctorName(primaryDoctorName);
            vitalSignHistory.setPreferredPharmacy(preferredPharmacy);

            JOptionPane.showMessageDialog(null, "Patient Created Successfully: " + vitalSignHistory.getPatientName());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid input !!!");
        }
        
    }//GEN-LAST:event_okayJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton okayJButton;
    private javax.swing.JTextField patientIDJTextField;
    private javax.swing.JTextField patientNameJTextField;
    private javax.swing.JTextField preferredPharmacyJTextField;
    private javax.swing.JTextField primaryDoctorNameJTextField;
    // End of variables declaration//GEN-END:variables
}
